### ISSUE TITLE
Migrate from SVN to Git

### ISSUE THREAD

**Issue by julen** [translate/translate-project#2113]
Depends on:
- [x] translate/pootle#2114 Complete AUTHORS mapping file
- [x] #2115 Migrate amaGama to Git
- [x] #2116 Migrate Corpuscatcher to Git
- [x] #2117 Migrate Spelt to Git
- [x] #2118 Migrate Translate Toolkit to Git
- [x] #2119 Migrate Virtaal to Git
- [x] #2120 Migrate Pootle to Git
- [x] #2130 Migrate mtscripts to Git

(Selected 'Pootle' as a component because didn't have a better choice)

We want to migrate our current SVN infrastructure to Git for all the products: Translate Toolkit, Pootle, Virtaal, Amagama and any other project that's hosted in SVN.

This is a bug to track everything related to that move.
