### ISSUE TITLE
[TRACKER] Static websites for all the products

### ISSUE THREAD

**Issue by julen** [translate/translate-project#2542]
Depends on:
- [x] #2543 Create generic layout for static websites
- [x] #2544 [Pootle] Setup static website
- [x] #2545 [Toolkit] Setup static website
- [x] #2546 [Virtaal] Setup static website
- [x] #2547 [amaGama] Setup static website

We need to create static showcase websites for our products, including Pootle, TT, Virtaal, and amaGama.

Each site should include a descriptive introduction, a list of features, download buttons, link to docs and repositories, and screenshots (when applicable).

Ideally each product should be separated in its own virtual space (subdomain or similar).
