### ISSUE TITLE
[TRACKER] All licensing related issues in our code

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate-project#2802]
Depends on:
- [ ] translate/virtaal#1082 Link to GPL not working
- [ ] translate/translate#2126 Confirm whether Apache-2.0 patches used in GPL-2.0+ licensed translate-toolkit 1.9.0
- [ ] translate/translate#2795 Clarify license of stoplist-en
- [ ] translate/translate#2799 Clarify license version for toolkit

This is a tracker for current licensing issues in our code.

This work should include:
1) Checking what the status of our current license is/are.
2) Working out how to credit and change headers in our multi-contributor model
3) Reviewing the AUTHORS files
4) Checking that with the repo split into products that credits are correct
5) Review all given credits and add people as needed.

License change related:
1) We've wanted to move to GPL3+
2) The impact of license on deployment on phone e.g. Android and iPhone

Imported code:
1) We have some bugs related to code we use from elsewhere.  We need to check that it is correctly licensd
2) Create a list of licenses for code that we use
3) Check for license incompatibilities.

And lastly if worst comes to worst.  Run an audit and copyright relicensing effort.
